name: Bug report
description: Report incorrect behavior
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
  - type: input
    id: version
    attributes:
      label: Version or commit
