/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: 'var(--vf-primary)',
        'surface-tint': 'var(--vf-surface-tint)',
        'primary-container': 'var(--vf-primary-container)',
        'on-primary': 'var(--vf-on-primary)',
        'on-primary-container': 'var(--vf-on-primary-container)',
        'on-primary-fixed': 'var(--vf-primary-fixed)',
        'primary-fixed': 'var(--vf-primary-fixed)',
        'primary-fixed-dim': 'var(--vf-primary-fixed-dim)',
        'inverse-primary': 'var(--vf-inverse-primary)',
        secondary: 'var(--vf-secondary)',
        'on-secondary': 'var(--vf-on-secondary)',
        'secondary-container': 'var(--vf-secondary-container)',
        'secondary-fixed': 'var(--vf-secondary-fixed)',
        'secondary-fixed-dim': 'var(--vf-secondary-fixed-dim)',
        tertiary: 'var(--vf-tertiary)',
        'on-tertiary': 'var(--vf-on-tertiary)',
        'tertiary-container': 'var(--vf-tertiary-container)',
        'on-tertiary-container': 'var(--vf-on-tertiary-container)',
        'tertiary-fixed-dim': 'var(--vf-tertiary-fixed-dim)',
        background: 'var(--vf-background)',
        'on-background': 'var(--vf-on-background)',
        surface: 'var(--vf-surface)',
        'surface-bright': 'var(--vf-surface-bright)',
        'surface-dim': 'var(--vf-surface-dim)',
        'surface-variant': 'var(--vf-surface-variant)',
        'on-surface': 'var(--vf-on-surface)',
        'on-surface-variant': 'var(--vf-on-surface-variant)',
        'surface-container-lowest': 'var(--vf-surface-container-lowest)',
        'surface-container-low': 'var(--vf-surface-container-low)',
        'surface-container': 'var(--vf-surface-container)',
        'surface-container-high': 'var(--vf-surface-container-high)',
        'surface-container-highest': 'var(--vf-surface-container-highest)',
        'inverse-surface': 'var(--vf-inverse-surface)',
        'inverse-on-surface': 'var(--vf-inverse-on-surface)',
        outline: 'var(--vf-outline)',
        'outline-variant': 'var(--vf-outline-variant)',
        error: 'var(--vf-error)',
        'on-error': 'var(--vf-on-error)',
        'error-container': 'var(--vf-error-container)',
        'on-error-container': 'var(--vf-on-error-container)',
        card: 'var(--vf-card)',
        'card-border': 'var(--vf-card-border)',
        success: 'var(--vf-success)',
        'success-muted': 'var(--vf-success-muted)',
        warning: 'var(--vf-warning)',
        'warning-muted': 'var(--vf-warning-muted)',
        brand: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#2563eb',
          600: '#1d4ed8',
          700: '#1e40af',
          800: '#1e3a8a',
          900: '#172554',
        },
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'sidebar-collapsed': '80px',
        'sidebar-expanded': '256px',
        'margin-desktop': '64px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        sans: ['"JetBrains Mono"', 'JetBrainsMono', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
        mono: ['"JetBrains Mono"', 'JetBrainsMono', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      fontSize: {
        'display-hero': ['36px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-base': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-semibold': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'data-mono': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
      maxWidth: {
        content: '100rem',
      },
      boxShadow: {
        'nav-active': '0 0 15px var(--vf-nav-glow)',
        'btn-primary': '0 0 10px var(--vf-nav-glow)',
      },
    },
  },
  plugins: [],
};
